[package]
name = "resw"
version = "0.1.1"
authors = ["Robert Masen <r@robertmasen.pizza>"]
edition = "2018"
description = "A library for writing RESSA AST parts to a file"
license = "MIT"
readme = "./README.md"
repository = "https://github.com/FreeMasen/RESW"


[dependencies]
ressa = "0.3"
log = "0.4"
pretty_env_logger = "0.3"
ress = "0.6"